-- Tabelas do projeto ForgeFit

CREATE TABLE PROFESSOR (
    ID SERIAL PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE
);

CREATE TABLE ALUNO (
    MATRICULA VARCHAR(20) PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    CREDITOS DECIMAL(10,2),
    PONTUACAO_TOTAL INTEGER,
    GUILDA_ID INTEGER
);

CREATE TABLE AVALIACAO_FISICA (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_AVALIACAO DATE NOT NULL,
    PROFESSOR_RESPONSAVEL_ID INTEGER NOT NULL,
    INDICE_DE_MASSA_CORPORAL DECIMAL(5,2),
    MASSA_GORDA_PERCENTUAL DECIMAL(5,2),
    MASSA_MAGRA_KG DECIMAL(5,2),
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA)
);

CREATE TABLE AULA (
    ID SERIAL PRIMARY KEY,
    PROFESSOR_ID INTEGER NOT NULL,
    MODALIDADE VARCHAR(50) NOT NULL,
    ESPACO VARCHAR(50) NOT NULL,
    CAPACIDADE INTEGER NOT NULL,
    INICIO TIMESTAMP NOT NULL,
    FIM TIMESTAMP NOT NULL
);

CREATE TABLE RECORRENCIA (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    DATA_FIM_RECORRENCIA DATE,
    FOREIGN KEY (AULA_ID) REFERENCES AULA(ID)
);

CREATE TABLE RECORRENCIA_DIAS (
    RECORRENCIA_ID INTEGER NOT NULL,
    DIA_DA_SEMANA VARCHAR(20) NOT NULL,
    FOREIGN KEY (RECORRENCIA_ID) REFERENCES RECORRENCIA(ID)
);

CREATE TABLE RESERVA (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_RESERVA TIMESTAMP NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    FOREIGN KEY (AULA_ID) REFERENCES AULA(ID)
);

CREATE TABLE GUILDA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    IMAGEM_URL VARCHAR(500),
    CODIGO_CONVITE VARCHAR(50) UNIQUE,
    MESTRE_MATRICULA VARCHAR(20) NOT NULL,
    PONTUACAO_TOTAL INTEGER
);

CREATE TABLE GUILDA_MEMBROS (
    GUILDA_ID INTEGER NOT NULL,
    MEMBRO_MATRICULA VARCHAR(20) NOT NULL,
    FOREIGN KEY (GUILDA_ID) REFERENCES GUILDA(ID)
);
