-- ============================================
-- FORGEFIT - MODELO FÍSICO DO BANCO DE DADOS
-- Baseado no Context Mapper Language (CML)
-- ============================================

-- ============================================
-- AGGREGATE: PROFESSOR
-- ============================================

CREATE TABLE PROFESSOR (
    ID SERIAL PRIMARY KEY,
    USER_ID VARCHAR(255),
    CPF VARCHAR(11) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    
    CONSTRAINT chk_professor_cpf_formato CHECK (CPF ~ '^\d{11}$')
);

CREATE INDEX idx_professor_user_id ON PROFESSOR(USER_ID);
COMMENT ON TABLE PROFESSOR IS 'Aggregate Root: Professor - Profissional responsável por aulas e avaliações';
COMMENT ON COLUMN PROFESSOR.USER_ID IS 'ID do usuário no sistema de autenticação externo';

-- ============================================
-- AGGREGATE: ALUNO
-- ============================================

CREATE TABLE ALUNO (
    MATRICULA VARCHAR(20) PRIMARY KEY,
    USER_ID VARCHAR(255),
    CPF VARCHAR(11) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    PONTUACAO_TOTAL INTEGER DEFAULT 0 NOT NULL,
    CREDITOS DECIMAL(10,2) DEFAULT 0.00 NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ATIVO' NOT NULL,
    GUILDA_ID INTEGER,
    PLANO_ATIVO_ID INTEGER,
    BLOQUEIO_ATE TIMESTAMP,
    
    CONSTRAINT chk_aluno_cpf_formato CHECK (CPF ~ '^\d{11}$'),
    CONSTRAINT chk_aluno_status CHECK (STATUS IN ('ATIVO', 'BLOQUEADO')),
    CONSTRAINT chk_aluno_creditos CHECK (CREDITOS >= 0),
    CONSTRAINT chk_aluno_pontuacao CHECK (PONTUACAO_TOTAL >= 0)
);

CREATE INDEX idx_aluno_user_id ON ALUNO(USER_ID);
CREATE INDEX idx_aluno_guilda ON ALUNO(GUILDA_ID);
CREATE INDEX idx_aluno_status ON ALUNO(STATUS);
COMMENT ON TABLE ALUNO IS 'Aggregate Root: Aluno - Estudante que participa de aulas e possui histórico';

-- Value Object: AvaliacaoFisica (embedded no histórico do Aluno)
CREATE TABLE AVALIACAO_FISICA (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_AVALIACAO DATE NOT NULL,
    PROFESSOR_RESPONSAVEL_ID INTEGER NOT NULL,
    
    -- Composição corporal
    MASSA_GORDA_PERCENTUAL DECIMAL(5,2),
    MASSA_GORDA_KG DECIMAL(6,2),
    MASSA_MAGRA_KG DECIMAL(6,2),
    MASSA_MUSCULAR_ESQUELETICA_KG DECIMAL(6,2),
    AGUA_CORPORAL_TOTAL_PERCENTUAL DECIMAL(5,2),
    GORDURA_VISCERAL_NIVEL INTEGER,
    TAXA_METABOLICA_BASAL_KCAL INTEGER,
    MASSA_OSSEA_KG DECIMAL(5,2),
    INDICE_DE_MASSA_CORPORAL DECIMAL(5,2),
    
    -- Medidas antropométricas
    BRACO_RELAXADO_CM DECIMAL(5,2),
    BRACO_CONTRAIDO_CM DECIMAL(5,2),
    ANTEBRACO_CM DECIMAL(5,2),
    TORAX_PEITORAL_CM DECIMAL(6,2),
    CINTURA_CM DECIMAL(6,2),
    ABDOMEN_CM DECIMAL(6,2),
    QUADRIL_CM DECIMAL(6,2),
    COXA_CM DECIMAL(6,2),
    PANTURRILHA_CM DECIMAL(5,2),
    
    CONSTRAINT fk_avaliacao_fisica_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE,
    CONSTRAINT fk_avaliacao_fisica_professor FOREIGN KEY (PROFESSOR_RESPONSAVEL_ID) REFERENCES PROFESSOR(ID)
);

CREATE INDEX idx_avaliacao_fisica_aluno ON AVALIACAO_FISICA(ALUNO_MATRICULA);
CREATE INDEX idx_avaliacao_fisica_data ON AVALIACAO_FISICA(DATA_AVALIACAO);
COMMENT ON TABLE AVALIACAO_FISICA IS 'Value Object: Histórico de avaliações físicas do aluno';

-- ============================================
-- AGGREGATE: PLANO DE TREINO
-- ============================================

CREATE TABLE PLANO_DE_TREINO (
    ID SERIAL PRIMARY KEY,
    PROFESSOR_RESPONSAVEL_ID INTEGER NOT NULL,
    DATA_CRIACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    DATA_VALIDADE_SUGERIDA DATE,
    
    CONSTRAINT fk_plano_treino_professor FOREIGN KEY (PROFESSOR_RESPONSAVEL_ID) REFERENCES PROFESSOR(ID)
);

CREATE INDEX idx_plano_treino_professor ON PLANO_DE_TREINO(PROFESSOR_RESPONSAVEL_ID);
COMMENT ON TABLE PLANO_DE_TREINO IS 'Aggregate Root: PlanoDeTreino - Plano de exercícios personalizado';

-- Value Object: TreinoDiario
CREATE TABLE TREINO_DIARIO (
    ID SERIAL PRIMARY KEY,
    PLANO_TREINO_ID INTEGER NOT NULL,
    LETRA VARCHAR(10) NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    
    CONSTRAINT fk_treino_diario_plano FOREIGN KEY (PLANO_TREINO_ID) REFERENCES PLANO_DE_TREINO(ID) ON DELETE CASCADE,
    CONSTRAINT chk_treino_letra CHECK (LETRA IN ('TREINO_A', 'TREINO_B', 'TREINO_C', 'TREINO_D', 'TREINO_E', 'TREINO_F', 'TREINO_G')),
    CONSTRAINT chk_treino_tipo CHECK (TIPO IN ('SUPERIORES', 'INFERIORES', 'CORPO_INTEIRO', 'PUSH', 'PULL', 'PERNAS',
        'PEITO_E_TRICEPS', 'COSTAS_E_BICEPS', 'OMBROS_E_TRAPEZIO', 'BRACOS_COMPLETOS',
        'PEITO_E_BICEPS', 'COSTAS_E_TRICEPS', 'FOCO_PEITO', 'FOCO_COSTAS', 'FOCO_OMBROS',
        'FOCO_GLUTEOS', 'ABDOMEN_E_CORE', 'PANTURRILHAS', 'CARDIO'))
);

CREATE INDEX idx_treino_diario_plano ON TREINO_DIARIO(PLANO_TREINO_ID);
COMMENT ON TABLE TREINO_DIARIO IS 'Value Object: Treino diário dentro do plano';

-- Value Object: ItemDeExercicio e Repeticao
CREATE TABLE ITEM_DE_EXERCICIO (
    ID SERIAL PRIMARY KEY,
    TREINO_DIARIO_ID INTEGER NOT NULL,
    ORDEM INTEGER NOT NULL,
    EXERCICIO VARCHAR(100) NOT NULL,
    SERIES INTEGER NOT NULL,
    CONTAGEM VARCHAR(50) NOT NULL,
    
    CONSTRAINT fk_item_exercicio_treino FOREIGN KEY (TREINO_DIARIO_ID) REFERENCES TREINO_DIARIO(ID) ON DELETE CASCADE,
    CONSTRAINT chk_exercicio_series CHECK (SERIES > 0)
);

CREATE INDEX idx_item_exercicio_treino ON ITEM_DE_EXERCICIO(TREINO_DIARIO_ID);
COMMENT ON TABLE ITEM_DE_EXERCICIO IS 'Value Object: Exercício específico no treino diário';
COMMENT ON COLUMN ITEM_DE_EXERCICIO.CONTAGEM IS 'Exemplo: 8-12, 15, 30s, etc.';

-- Relação com histórico do Aluno
CREATE TABLE ALUNO_PLANO_HISTORICO (
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    PLANO_TREINO_ID INTEGER NOT NULL,
    DATA_ATRIBUICAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (ALUNO_MATRICULA, PLANO_TREINO_ID),
    CONSTRAINT fk_historico_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE,
    CONSTRAINT fk_historico_plano FOREIGN KEY (PLANO_TREINO_ID) REFERENCES PLANO_DE_TREINO(ID) ON DELETE CASCADE
);

ALTER TABLE ALUNO ADD CONSTRAINT fk_aluno_plano_ativo FOREIGN KEY (PLANO_ATIVO_ID) REFERENCES PLANO_DE_TREINO(ID);

-- ============================================
-- AGGREGATE: AULA
-- ============================================

CREATE TABLE AULA (
    ID SERIAL PRIMARY KEY,
    PROFESSOR_ID INTEGER NOT NULL,
    MODALIDADE VARCHAR(50) NOT NULL,
    ESPACO VARCHAR(50) NOT NULL,
    CAPACIDADE INTEGER NOT NULL,
    INICIO TIMESTAMP NOT NULL,
    FIM TIMESTAMP NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ATIVA' NOT NULL,
    
    CONSTRAINT fk_aula_professor FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(ID),
    CONSTRAINT chk_aula_capacidade CHECK (CAPACIDADE > 0),
    CONSTRAINT chk_aula_horario CHECK (FIM > INICIO),
    CONSTRAINT chk_aula_status CHECK (STATUS IN ('ATIVA', 'CANCELADA', 'CONCLUIDA')),
    CONSTRAINT chk_aula_modalidade CHECK (MODALIDADE IN ('MUSCULACAO', 'SPINNING', 'YOGA', 'BOXE', 'CROSSFIT', 
        'PILATES', 'ZUMBA', 'FUNCIONAL', 'JIUJITSU', 'MUAYTHAI', 'DANCA')),
    CONSTRAINT chk_aula_espaco CHECK (ESPACO IN ('SALA01_MULTIUSO', 'SALA02_MULTIUSO', 'SALA03_SPINNING', 
        'ESTUDIO_PILATES', 'AREA_DE_LUTAS', 'AREA_DE_PESO_LIVRE'))
);

CREATE INDEX idx_aula_professor ON AULA(PROFESSOR_ID);
CREATE INDEX idx_aula_inicio ON AULA(INICIO);
CREATE INDEX idx_aula_espaco ON AULA(ESPACO);
CREATE INDEX idx_aula_status ON AULA(STATUS);
COMMENT ON TABLE AULA IS 'Aggregate Root: Aula - Sessão de treino ministrada por professor';

-- Value Object: Recorrencia
CREATE TABLE RECORRENCIA (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL UNIQUE,
    TIPO VARCHAR(20) NOT NULL,
    DATA_FIM_RECORRENCIA DATE,
    
    CONSTRAINT fk_recorrencia_aula FOREIGN KEY (AULA_ID) REFERENCES AULA(ID) ON DELETE CASCADE,
    CONSTRAINT chk_recorrencia_tipo CHECK (TIPO IN ('SEMANAL', 'MENSAL', 'SEMESTRAL', 'ANUAL'))
);

COMMENT ON TABLE RECORRENCIA IS 'Value Object: Padrão de recorrência da aula';

CREATE TABLE RECORRENCIA_DIAS (
    RECORRENCIA_ID INTEGER NOT NULL,
    DIA_DA_SEMANA VARCHAR(20) NOT NULL,
    
    PRIMARY KEY (RECORRENCIA_ID, DIA_DA_SEMANA),
    CONSTRAINT fk_recorrencia_dias FOREIGN KEY (RECORRENCIA_ID) REFERENCES RECORRENCIA(ID) ON DELETE CASCADE,
    CONSTRAINT chk_dia_semana CHECK (DIA_DA_SEMANA IN ('DOMINGO', 'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO'))
);

COMMENT ON TABLE RECORRENCIA_DIAS IS 'Dias da semana em que a aula recorrente acontece';

-- Entity: OcorrenciaExcecao
CREATE TABLE OCORRENCIA_EXCECAO (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL,
    DATA_ORIGINAL_OCORRENCIA DATE NOT NULL,
    CANCELADA BOOLEAN DEFAULT FALSE NOT NULL,
    NOVO_INICIO TIMESTAMP,
    NOVO_FIM TIMESTAMP,
    
    CONSTRAINT fk_ocorrencia_aula FOREIGN KEY (AULA_ID) REFERENCES AULA(ID) ON DELETE CASCADE,
    CONSTRAINT chk_excecao_horario CHECK (NOVO_FIM IS NULL OR NOVO_FIM > NOVO_INICIO)
);

CREATE INDEX idx_ocorrencia_aula ON OCORRENCIA_EXCECAO(AULA_ID);
COMMENT ON TABLE OCORRENCIA_EXCECAO IS 'Entity: Exceções/alterações em ocorrências específicas de aula recorrente';

-- Value Object: Reserva
CREATE TABLE RESERVA (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_RESERVA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'CONFIRMADA' NOT NULL,
    
    CONSTRAINT fk_reserva_aula FOREIGN KEY (AULA_ID) REFERENCES AULA(ID) ON DELETE CASCADE,
    CONSTRAINT fk_reserva_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE,
    CONSTRAINT chk_reserva_status CHECK (STATUS IN ('CONFIRMADA', 'CANCELADA_PELO_ALUNO', 'CANCELADA_PELA_ACADEMIA')),
    CONSTRAINT uk_reserva_aluno_aula UNIQUE (AULA_ID, ALUNO_MATRICULA)
);

CREATE INDEX idx_reserva_aula ON RESERVA(AULA_ID);
CREATE INDEX idx_reserva_aluno ON RESERVA(ALUNO_MATRICULA);
COMMENT ON TABLE RESERVA IS 'Value Object: Reserva de vaga em aula';

-- Value Object: PosicaoListaDeEspera
CREATE TABLE LISTA_DE_ESPERA (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    TIMESTAMP_ENTRADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT fk_lista_espera_aula FOREIGN KEY (AULA_ID) REFERENCES AULA(ID) ON DELETE CASCADE,
    CONSTRAINT fk_lista_espera_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE,
    CONSTRAINT uk_lista_espera_aluno_aula UNIQUE (AULA_ID, ALUNO_MATRICULA)
);

CREATE INDEX idx_lista_espera_aula ON LISTA_DE_ESPERA(AULA_ID);
CREATE INDEX idx_lista_espera_timestamp ON LISTA_DE_ESPERA(TIMESTAMP_ENTRADA);
COMMENT ON TABLE LISTA_DE_ESPERA IS 'Value Object: Posição na fila de espera para aula lotada';

-- ============================================
-- AGGREGATE: FREQUENCIA (Value Object no histórico do Aluno)
-- ============================================

CREATE TABLE FREQUENCIA (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    AULA_ID INTEGER NOT NULL,
    DATA_OCORRENCIA DATE NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PRESENTE' NOT NULL,
    
    CONSTRAINT fk_frequencia_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE,
    CONSTRAINT fk_frequencia_aula FOREIGN KEY (AULA_ID) REFERENCES AULA(ID) ON DELETE CASCADE,
    CONSTRAINT chk_frequencia_status CHECK (STATUS IN ('PRESENTE', 'FALTA')),
    CONSTRAINT uk_frequencia_aluno_aula_data UNIQUE (ALUNO_MATRICULA, AULA_ID, DATA_OCORRENCIA)
);

CREATE INDEX idx_frequencia_aluno ON FREQUENCIA(ALUNO_MATRICULA);
CREATE INDEX idx_frequencia_data ON FREQUENCIA(DATA_OCORRENCIA);
COMMENT ON TABLE FREQUENCIA IS 'Value Object: Registro de presença/falta do aluno em aula';

-- ============================================
-- AGGREGATE: GUILDA
-- ============================================

CREATE TABLE GUILDA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL UNIQUE,
    DESCRICAO TEXT,
    IMAGEM_URL VARCHAR(500),
    STATUS VARCHAR(20) DEFAULT 'ATIVA' NOT NULL,
    CODIGO_CONVITE VARCHAR(50) NOT NULL UNIQUE,
    MESTRE_MATRICULA VARCHAR(20) NOT NULL,
    PONTUACAO_TOTAL INTEGER DEFAULT 0 NOT NULL,
    
    CONSTRAINT fk_guilda_mestre FOREIGN KEY (MESTRE_MATRICULA) REFERENCES ALUNO(MATRICULA),
    CONSTRAINT chk_guilda_status CHECK (STATUS IN ('ATIVA', 'INATIVA')),
    CONSTRAINT chk_guilda_pontuacao CHECK (PONTUACAO_TOTAL >= 0)
);

CREATE INDEX idx_guilda_codigo ON GUILDA(CODIGO_CONVITE);
CREATE INDEX idx_guilda_mestre ON GUILDA(MESTRE_MATRICULA);
COMMENT ON TABLE GUILDA IS 'Aggregate Root: Guilda - Grupo de alunos para gamificação';

CREATE TABLE GUILDA_MEMBROS (
    GUILDA_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_ENTRADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    PRIMARY KEY (GUILDA_ID, ALUNO_MATRICULA),
    CONSTRAINT fk_guilda_membros_guilda FOREIGN KEY (GUILDA_ID) REFERENCES GUILDA(ID) ON DELETE CASCADE,
    CONSTRAINT fk_guilda_membros_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE
);

ALTER TABLE ALUNO ADD CONSTRAINT fk_aluno_guilda FOREIGN KEY (GUILDA_ID) REFERENCES GUILDA(ID);

-- ============================================
-- AGGREGATE: TORNEIO
-- ============================================

CREATE TABLE TORNEIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'PLANEJADO' NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    
    -- Prêmios (Value Object: Premio)
    PREMIO_PRIMEIRO_LUGAR_NOME VARCHAR(255),
    PREMIO_PRIMEIRO_LUGAR_URL_IMAGEM VARCHAR(500),
    PREMIO_SEGUNDO_LUGAR_NOME VARCHAR(255),
    PREMIO_SEGUNDO_LUGAR_URL_IMAGEM VARCHAR(500),
    PREMIO_TERCEIRO_LUGAR_NOME VARCHAR(255),
    PREMIO_TERCEIRO_LUGAR_URL_IMAGEM VARCHAR(500),
    
    CONSTRAINT chk_torneio_status CHECK (STATUS IN ('PLANEJADO', 'ATIVO', 'FINALIZADO', 'CANCELADO')),
    CONSTRAINT chk_torneio_datas CHECK (DATA_FIM >= DATA_INICIO)
);

CREATE INDEX idx_torneio_status ON TORNEIO(STATUS);
CREATE INDEX idx_torneio_datas ON TORNEIO(DATA_INICIO, DATA_FIM);
COMMENT ON TABLE TORNEIO IS 'Aggregate Root: Torneio - Competição entre guildas';

-- Value Object: PosicaoRanking (parte do ranking final do torneio)
CREATE TABLE TORNEIO_RANKING_FINAL (
    ID SERIAL PRIMARY KEY,
    TORNEIO_ID INTEGER NOT NULL,
    POSICAO INTEGER NOT NULL,
    GUILDA_ID INTEGER NOT NULL,
    PONTUACAO_NO_TORNEIO INTEGER NOT NULL,
    
    CONSTRAINT fk_torneio_ranking_torneio FOREIGN KEY (TORNEIO_ID) REFERENCES TORNEIO(ID) ON DELETE CASCADE,
    CONSTRAINT fk_torneio_ranking_guilda FOREIGN KEY (GUILDA_ID) REFERENCES GUILDA(ID),
    CONSTRAINT uk_torneio_posicao UNIQUE (TORNEIO_ID, POSICAO),
    CONSTRAINT uk_torneio_guilda UNIQUE (TORNEIO_ID, GUILDA_ID)
);

CREATE INDEX idx_torneio_ranking ON TORNEIO_RANKING_FINAL(TORNEIO_ID);
COMMENT ON TABLE TORNEIO_RANKING_FINAL IS 'Value Object: Classificação final do torneio';

-- ============================================
-- AGGREGATE: AVALIACAO
-- ============================================

CREATE TABLE AVALIACAO (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    PROFESSOR_ID INTEGER NOT NULL,
    AULA_ID INTEGER NOT NULL,
    DATA_OCORRENCIA_AULA DATE NOT NULL,
    
    -- Value Object: Notas
    NOTA_PONTUALIDADE INTEGER NOT NULL,
    NOTA_DIDATICA INTEGER NOT NULL,
    NOTA_ATENCAO INTEGER NOT NULL,
    
    COMENTARIO TEXT,
    DATA_AVALIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    
    CONSTRAINT fk_avaliacao_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE,
    CONSTRAINT fk_avaliacao_professor FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(ID),
    CONSTRAINT fk_avaliacao_aula FOREIGN KEY (AULA_ID) REFERENCES AULA(ID),
    CONSTRAINT chk_avaliacao_pontualidade CHECK (NOTA_PONTUALIDADE BETWEEN 0 AND 5),
    CONSTRAINT chk_avaliacao_didatica CHECK (NOTA_DIDATICA BETWEEN 0 AND 5),
    CONSTRAINT chk_avaliacao_atencao CHECK (NOTA_ATENCAO BETWEEN 0 AND 5),
    CONSTRAINT uk_avaliacao_unica UNIQUE (ALUNO_MATRICULA, AULA_ID, DATA_OCORRENCIA_AULA)
);

CREATE INDEX idx_avaliacao_professor ON AVALIACAO(PROFESSOR_ID);
CREATE INDEX idx_avaliacao_aluno ON AVALIACAO(ALUNO_MATRICULA);
CREATE INDEX idx_avaliacao_aula ON AVALIACAO(AULA_ID);
COMMENT ON TABLE AVALIACAO IS 'Aggregate Root: Avaliação do professor pelo aluno';

-- ============================================
-- AGGREGATE: CHECKIN
-- ============================================

CREATE TABLE CHECKIN (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    GUILDA_ID INTEGER,
    DATA_CHECKIN TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PONTUACAO_TOTAL INTEGER NOT NULL,
    MENSAGEM TEXT,
    URL_IMAGEM VARCHAR(500),
    
    -- Value Object: ContextoDoCheckin
    CONTEXTO_TIPO VARCHAR(20) NOT NULL,
    CONTEXTO_AULA_ID INTEGER,
    CONTEXTO_PLANO_TREINO_ID INTEGER,
    CONTEXTO_LETRA_TREINO VARCHAR(10),
    
    CONSTRAINT fk_checkin_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE,
    CONSTRAINT fk_checkin_guilda FOREIGN KEY (GUILDA_ID) REFERENCES GUILDA(ID),
    CONSTRAINT fk_checkin_aula FOREIGN KEY (CONTEXTO_AULA_ID) REFERENCES AULA(ID),
    CONSTRAINT fk_checkin_plano FOREIGN KEY (CONTEXTO_PLANO_TREINO_ID) REFERENCES PLANO_DE_TREINO(ID),
    CONSTRAINT chk_checkin_tipo CHECK (CONTEXTO_TIPO IN ('AULA', 'TREINO')),
    CONSTRAINT chk_checkin_pontuacao CHECK (PONTUACAO_TOTAL >= 0)
);

CREATE INDEX idx_checkin_aluno ON CHECKIN(ALUNO_MATRICULA);
CREATE INDEX idx_checkin_guilda ON CHECKIN(GUILDA_ID);
CREATE INDEX idx_checkin_data ON CHECKIN(DATA_CHECKIN);
COMMENT ON TABLE CHECKIN IS 'Aggregate Root: Check-in de treino/aula do aluno';

-- ============================================
-- AGGREGATE: RANKING
-- ============================================

CREATE TABLE RANKING (
    ID SERIAL PRIMARY KEY,
    PERIODO VARCHAR(20) NOT NULL,
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT chk_ranking_periodo CHECK (PERIODO IN ('SEMANAL', 'MENSAL', 'GERAL')),
    CONSTRAINT uk_ranking_periodo UNIQUE (PERIODO)
);

COMMENT ON TABLE RANKING IS 'Aggregate Root: Ranking de alunos por período';

-- Value Object: ItemRanking
CREATE TABLE ITEM_RANKING (
    ID SERIAL PRIMARY KEY,
    RANKING_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    PONTOS_FREQUENCIA INTEGER DEFAULT 0 NOT NULL,
    PONTOS_GUILDA INTEGER DEFAULT 0 NOT NULL,
    PONTOS_PERFORMANCE INTEGER DEFAULT 0 NOT NULL,
    PONTUACAO_TOTAL INTEGER DEFAULT 0 NOT NULL,
    POSICAO INTEGER NOT NULL,
    NUMERO_AULAS_PARTICIPADAS INTEGER DEFAULT 0,
    MEDIA_PERFORMANCE DECIMAL(5,2) DEFAULT 0.00,
    NUMERO_AVALIACOES INTEGER DEFAULT 0,
    
    CONSTRAINT fk_item_ranking_ranking FOREIGN KEY (RANKING_ID) REFERENCES RANKING(ID) ON DELETE CASCADE,
    CONSTRAINT fk_item_ranking_aluno FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA) ON DELETE CASCADE,
    CONSTRAINT uk_item_ranking_aluno UNIQUE (RANKING_ID, ALUNO_MATRICULA),
    CONSTRAINT uk_item_ranking_posicao UNIQUE (RANKING_ID, POSICAO)
);

CREATE INDEX idx_item_ranking_ranking ON ITEM_RANKING(RANKING_ID);
CREATE INDEX idx_item_ranking_posicao ON ITEM_RANKING(POSICAO);
COMMENT ON TABLE ITEM_RANKING IS 'Value Object: Posição e pontos de um aluno no ranking';

-- ============================================
-- FIM DO SCRIPT DE CRIAÇÃO
-- ============================================

-- Observações importantes:
-- 1. Todas as entidades agregadas seguem o padrão do CML
-- 2. Value Objects são embedded ou tabelas separadas conforme complexidade
-- 3. FKs com ON DELETE CASCADE para garantir integridade referencial
-- 4. Constraints CHECK para validar enums e regras de negócio
-- 5. Índices criados para otimizar buscas frequentes
-- 6. UNIQUE constraints para garantir unicidade de dados importantes
