-- Tabelas do projeto ForgeFit

-- ============================================
-- TABELAS PRINCIPAIS
-- ============================================

CREATE TABLE PROFESSOR (
    ID SERIAL PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    USER_ID VARCHAR(255)
);

CREATE TABLE ALUNO (
    MATRICULA VARCHAR(20) PRIMARY KEY,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE,
    USER_ID VARCHAR(255),
    CREDITOS DOUBLE PRECISION,
    PONTUACAO_TOTAL INTEGER,
    GUILDA_ID INTEGER,
    STATUS VARCHAR(20) DEFAULT 'ATIVO',
    PLANO_ATIVO_ID INTEGER,
    BLOQUEIO_ATE TIMESTAMP
);

CREATE TABLE AVALIACAO_FISICA (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_AVALIACAO DATE NOT NULL,
    PROFESSOR_RESPONSAVEL_ID INTEGER NOT NULL,
    INDICE_DE_MASSA_CORPORAL DECIMAL(5,2),
    MASSA_GORDA_PERCENTUAL DECIMAL(5,2),
    MASSA_MAGRA_KG DECIMAL(5,2),
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA),
    FOREIGN KEY (PROFESSOR_RESPONSAVEL_ID) REFERENCES PROFESSOR(ID)
);

CREATE TABLE AULA (
    ID SERIAL PRIMARY KEY,
    PROFESSOR_ID INTEGER NOT NULL,
    MODALIDADE VARCHAR(50) NOT NULL,
    ESPACO VARCHAR(50) NOT NULL,
    CAPACIDADE INTEGER NOT NULL,
    INICIO TIMESTAMP NOT NULL,
    FIM TIMESTAMP NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'ATIVA',
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(ID)
);

CREATE TABLE RECORRENCIA (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    DATA_FIM_RECORRENCIA DATE,
    FOREIGN KEY (AULA_ID) REFERENCES AULA(ID)
);

CREATE TABLE RECORRENCIA_DIAS (
    RECORRENCIA_ID INTEGER NOT NULL,
    DIA_DA_SEMANA VARCHAR(20) NOT NULL,
    FOREIGN KEY (RECORRENCIA_ID) REFERENCES RECORRENCIA(ID)
);

CREATE TABLE RESERVA (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_RESERVA TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'CONFIRMADA',
    FOREIGN KEY (AULA_ID) REFERENCES AULA(ID),
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA)
);

-- ============================================
-- TABELA DE AVALIAÇÃO DE PROFESSORES
-- ============================================

CREATE TABLE AVALIACAO (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    PROFESSOR_ID INTEGER NOT NULL,
    AULA_ID INTEGER NOT NULL,
    DATA_OCORRENCIA_AULA DATE NOT NULL,
    NOTA_PONTUALIDADE INTEGER NOT NULL CHECK (NOTA_PONTUALIDADE >= 0 AND NOTA_PONTUALIDADE <= 5),
    NOTA_DIDATICA INTEGER NOT NULL CHECK (NOTA_DIDATICA >= 0 AND NOTA_DIDATICA <= 5),
    NOTA_ATENCAO INTEGER NOT NULL CHECK (NOTA_ATENCAO >= 0 AND NOTA_ATENCAO <= 5),
    COMENTARIO VARCHAR(1000),
    DATA_AVALIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA),
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(ID),
    FOREIGN KEY (AULA_ID) REFERENCES AULA(ID),
    UNIQUE(ALUNO_MATRICULA, AULA_ID, DATA_OCORRENCIA_AULA)
);

-- ============================================
-- TABELA DE FALTAS
-- ============================================

CREATE TABLE FALTAS_REGISTRO (
    ID SERIAL PRIMARY KEY,
    CPF_ALUNO VARCHAR(11) NOT NULL,
    DATA_AULA DATE NOT NULL,
    AULA_ID INTEGER,
    CRIADO_EM TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AULA_ID) REFERENCES AULA(ID),
    UNIQUE(CPF_ALUNO, DATA_AULA, AULA_ID)
);

-- ============================================
-- TABELAS DE FREQUÊNCIA E CHECK-IN
-- ============================================

CREATE TABLE FREQUENCIA (
    ID SERIAL PRIMARY KEY,
    AULA_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_PRESENCA DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PRESENTE',
    FOREIGN KEY (AULA_ID) REFERENCES AULA(ID),
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA)
);

CREATE TABLE CHECKIN (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    TIMESTAMP_CHECKIN TIMESTAMP NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    AULA_ID INTEGER,
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA),
    FOREIGN KEY (AULA_ID) REFERENCES AULA(ID)
);

-- ============================================
-- TABELAS DE GUILDA
-- ============================================

CREATE TABLE GUILDA (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    IMAGEM_URL VARCHAR(500),
    CODIGO_CONVITE VARCHAR(50) UNIQUE,
    MESTRE_MATRICULA VARCHAR(20) NOT NULL,
    PONTUACAO_TOTAL INTEGER DEFAULT 0,
    STATUS VARCHAR(20) DEFAULT 'ATIVA',
    FOREIGN KEY (MESTRE_MATRICULA) REFERENCES ALUNO(MATRICULA)
);

CREATE TABLE GUILDA_MEMBROS (
    GUILDA_ID INTEGER NOT NULL,
    MEMBRO_MATRICULA VARCHAR(20) NOT NULL,
    DATA_ENTRADA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (GUILDA_ID, MEMBRO_MATRICULA),
    FOREIGN KEY (GUILDA_ID) REFERENCES GUILDA(ID),
    FOREIGN KEY (MEMBRO_MATRICULA) REFERENCES ALUNO(MATRICULA)
);

-- ============================================
-- TABELAS DE RANKING
-- ============================================

CREATE TABLE RANKING (
    ID SERIAL PRIMARY KEY,
    PERIODO VARCHAR(20) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ITEM_RANKING (
    ID SERIAL PRIMARY KEY,
    RANKING_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    POSICAO INTEGER NOT NULL,
    PONTUACAO INTEGER NOT NULL,
    FOREIGN KEY (RANKING_ID) REFERENCES RANKING(ID),
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA)
);

-- ============================================
-- TABELAS DE TORNEIO
-- ============================================

CREATE TABLE TORNEIO (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL DEFAULT 'PLANEJADO',
    PONTUACAO_MINIMA INTEGER,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE TORNEIO_PARTICIPANTES (
    TORNEIO_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    PONTUACAO INTEGER DEFAULT 0,
    PRIMARY KEY (TORNEIO_ID, ALUNO_MATRICULA),
    FOREIGN KEY (TORNEIO_ID) REFERENCES TORNEIO(ID),
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA)
);

CREATE TABLE TORNEIO_PODIO (
    ID SERIAL PRIMARY KEY,
    TORNEIO_ID INTEGER NOT NULL,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    POSICAO VARCHAR(20) NOT NULL,
    PREMIO_DESCRICAO VARCHAR(500),
    FOREIGN KEY (TORNEIO_ID) REFERENCES TORNEIO(ID),
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA)
);

-- ============================================
-- TABELAS DE PLANO DE TREINO
-- ============================================

CREATE TABLE PLANO_TREINO (
    ID SERIAL PRIMARY KEY,
    ALUNO_MATRICULA VARCHAR(20) NOT NULL,
    PROFESSOR_ID INTEGER NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    ATIVO BOOLEAN DEFAULT TRUE,
    CRIADO_EM TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ALUNO_MATRICULA) REFERENCES ALUNO(MATRICULA),
    FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR(ID)
);

CREATE TABLE TREINO_DIARIO (
    ID SERIAL PRIMARY KEY,
    PLANO_TREINO_ID INTEGER NOT NULL,
    LETRA_TREINO VARCHAR(1) NOT NULL,
    DIA_SEMANA VARCHAR(20),
    NOME VARCHAR(255),
    FOREIGN KEY (PLANO_TREINO_ID) REFERENCES PLANO_TREINO(ID)
);

CREATE TABLE ITEM_EXERCICIO (
    ID SERIAL PRIMARY KEY,
    TREINO_DIARIO_ID INTEGER NOT NULL,
    EXERCICIO VARCHAR(100) NOT NULL,
    ORDEM INTEGER NOT NULL,
    SERIES INTEGER,
    REPETICOES_MIN INTEGER,
    REPETICOES_MAX INTEGER,
    CARGA DECIMAL(5,2),
    DESCANSO_SEGUNDOS INTEGER,
    OBSERVACOES VARCHAR(500),
    FOREIGN KEY (TREINO_DIARIO_ID) REFERENCES TREINO_DIARIO(ID)
);

-- ============================================
-- ÍNDICES PARA PERFORMANCE
-- ============================================

CREATE INDEX idx_aluno_user_id ON ALUNO(USER_ID);
CREATE INDEX idx_professor_user_id ON PROFESSOR(USER_ID);
CREATE INDEX idx_aula_professor ON AULA(PROFESSOR_ID);
CREATE INDEX idx_aula_inicio ON AULA(INICIO);
CREATE INDEX idx_aula_status ON AULA(STATUS);
CREATE INDEX idx_reserva_aluno ON RESERVA(ALUNO_MATRICULA);
CREATE INDEX idx_reserva_aula ON RESERVA(AULA_ID);
CREATE INDEX idx_reserva_status ON RESERVA(STATUS);
CREATE INDEX idx_avaliacao_professor ON AVALIACAO(PROFESSOR_ID);
CREATE INDEX idx_avaliacao_aluno ON AVALIACAO(ALUNO_MATRICULA);
CREATE INDEX idx_faltas_cpf ON FALTAS_REGISTRO(CPF_ALUNO);
CREATE INDEX idx_faltas_data ON FALTAS_REGISTRO(DATA_AULA);
CREATE INDEX idx_frequencia_aluno ON FREQUENCIA(ALUNO_MATRICULA);
CREATE INDEX idx_checkin_aluno ON CHECKIN(ALUNO_MATRICULA);
CREATE INDEX idx_guilda_status ON GUILDA(STATUS);

-- ============================================
-- COMENTÁRIOS DAS TABELAS
-- ============================================

COMMENT ON TABLE AVALIACAO IS 'Avaliações de professores feitas pelos alunos após as aulas';
COMMENT ON TABLE FALTAS_REGISTRO IS 'Registro de faltas dos alunos nas aulas';
COMMENT ON COLUMN AULA.STATUS IS 'Status da aula: ATIVA, CANCELADA';
COMMENT ON COLUMN RESERVA.STATUS IS 'Status da reserva: CONFIRMADA, CANCELADA_PELO_ALUNO, CANCELADA_PELA_ACADEMIA';
COMMENT ON COLUMN ALUNO.STATUS IS 'Status do aluno: ATIVO, INATIVO, SUSPENSO';
COMMENT ON COLUMN GUILDA.STATUS IS 'Status da guilda: ATIVA, INATIVA';
