-- Dados iniciais do ForgeFit

INSERT INTO PROFESSOR(CPF, NOME, DATA_NASCIMENTO) VALUES (
    '05144786405',
    'João Silva',
    '1985-06-15'
);

INSERT INTO PROFESSOR(CPF, NOME, DATA_NASCIMENTO) VALUES (
    '03972009437',
    'Maria Santos',
    '1990-03-20'
);

INSERT INTO ALUNO(MATRICULA, CPF, NOME, DATA_NASCIMENTO, CREDITOS, PONTUACAO_TOTAL) VALUES (
    'ALU001',
    '85571506440',
    'Pedro Oliveira',
    '1995-09-10',
    100.0,
    50
);

INSERT INTO ALUNO(MATRICULA, CPF, NOME, DATA_NASCIMENTO, CREDITOS, PONTUACAO_TOTAL) VALUES (
    'ALU002',
    '22173582437',
    'Ana Costa',
    '1998-12-05',
    150.0,
    120
);

INSERT INTO AVALIACAO_FISICA(ALUNO_MATRICULA, DATA_AVALIACAO, PROFESSOR_RESPONSAVEL_ID, INDICE_DE_MASSA_CORPORAL, MASSA_GORDA_PERCENTUAL, MASSA_MAGRA_KG) VALUES (
    'ALU001',
    CURRENT_DATE,
    1,
    24.5,
    18.0,
    65.0
);

INSERT INTO AULA(PROFESSOR_ID, MODALIDADE, ESPACO, CAPACIDADE, INICIO, FIM) VALUES (
    2,
    'YOGA',
    'SALA01_MULTIUSO',
    15,
    '2025-01-20 10:00:00',
    '2025-01-20 11:00:00'
);

INSERT INTO RECORRENCIA(AULA_ID, TIPO, DATA_FIM_RECORRENCIA) VALUES (
    1,
    'SEMANAL',
    '2025-06-30'
);

INSERT INTO RECORRENCIA_DIAS(RECORRENCIA_ID, DIA_DA_SEMANA) VALUES (1, 'SEGUNDA');
INSERT INTO RECORRENCIA_DIAS(RECORRENCIA_ID, DIA_DA_SEMANA) VALUES (1, 'QUARTA');
INSERT INTO RECORRENCIA_DIAS(RECORRENCIA_ID, DIA_DA_SEMANA) VALUES (1, 'SEXTA');

INSERT INTO RESERVA(AULA_ID, ALUNO_MATRICULA, DATA_RESERVA, STATUS) VALUES (
    1,
    'ALU001',
    CURRENT_TIMESTAMP,
    'CONFIRMADA'
);

INSERT INTO AULA(PROFESSOR_ID, MODALIDADE, ESPACO, CAPACIDADE, INICIO, FIM) VALUES (
    1,
    'MUSCULACAO',
    'AREA_DE_PESO_LIVRE',
    20,
    '2025-01-21 14:00:00',
    '2025-01-21 15:30:00'
);

INSERT INTO GUILDA(NOME, DESCRICAO, IMAGEM_URL, CODIGO_CONVITE, MESTRE_MATRICULA, PONTUACAO_TOTAL) VALUES (
    'Guerreiros do Fitness',
    'Guilda para atletas dedicados',
    'https://example.com/guerreiros.png',
    'GUERR2025',
    'ALU001',
    170
);

INSERT INTO GUILDA_MEMBROS(GUILDA_ID, MEMBRO_MATRICULA) VALUES (1, 'ALU001');
INSERT INTO GUILDA_MEMBROS(GUILDA_ID, MEMBRO_MATRICULA) VALUES (1, 'ALU002');

UPDATE ALUNO SET GUILDA_ID = 1 WHERE MATRICULA IN ('ALU001', 'ALU002');
